services:
  backend:
    image: irfangustian/backend-drive-nip:latest
    restart: always
    networks:
      - app-network
      - proxy
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # Router untuk Backend API (HTTPS)
      - "traefik.http.routers.backend-api-secure.rule=Host(`filepppk.spyderwick.web.id`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-api-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-api-secure.tls.certresolver=myresolver"
      - "traefik.http.services.backend-api.loadbalancer.server.port=5000"

  frontend:
    image: irfangustian/frontend-nip-app:latest
    restart: always
    networks:
      - app-network
      - proxy
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Router untuk redirect HTTP ke HTTPS
      - "traefik.http.routers.frontend-app-http.rule=Host(`filepppk.spyderwick.web.id`)"
      - "traefik.http.routers.frontend-app-http.entrypoints=web"
      - "traefik.http.routers.frontend-app-http.middlewares=https-redirect"
      
      # Middleware untuk redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      
      # Router utama untuk Frontend App (HTTPS)
      - "traefik.http.routers.frontend-app-secure.rule=Host(`filepppk.spyderwick.web.id`)"
      - "traefik.http.routers.frontend-app-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-app-secure.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-app.loadbalancer.server.port=80"

networks:
  app-network:
    driver: bridge
  proxy:
    external: true