version: '3.8'

services:
  backend:
    image: irfangustian/backend-drive-nip:latest
    restart: always
    networks:
      - app-network
    # Port 5000 dari container akan di-expose ke port 3001 di VPS.
    # Anda bisa mengakses API backend langsung via http://[IP_VPS]:3001 jika diperlukan.
    ports:
      - "3001:5000"
    # Di sini Anda bisa menambahkan environment variables jika ada
    # environment:
    #   - DATABASE_URL=...
    #   - JWT_SECRET=...

  frontend:
    image: irfangustian/frontend-nip-app:latest
    restart: always
    networks:
      - app-network
    # Port 80 dari container (Nginx) akan di-expose ke port 80 di VPS.
    # Ini memungkinkan aplikasi diakses langsung via http://[IP_VPS]
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge