version: '3.8'

services:
  backend:
    build:
      context: ./backend-drive-nip
      dockerfile: Dockerfile
    image: irfangustian/backend-drive-nip:latest
    restart: always
    networks:
      - app-network
      - traefik-public
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.backend-api.rule=Host(`nip.domain.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-api.entrypoints=web"
      - "traefik.http.services.backend-api.loadbalancer.server.port=5000"

  frontend:
    build:
      context: ./frontend-nip-app
      dockerfile: Dockerfile
    image: irfangustian/frontend-nip-app:latest
    restart: always
    networks:
      - app-network
      - traefik-public
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.frontend-app.rule=Host(`nip.domain.com`)"
      - "traefik.http.routers.frontend-app.entrypoints=web"
      - "traefik.http.services.frontend-app.loadbalancer.server.port=80"

networks:
  app-network:
    driver: bridge
  traefik-public:
    external: true