services:
  backend:
    build: ./backend-drive-nip
    container_name: backend-drive-nip-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend-drive-nip/.env
    volumes:
      # Mounts the host's source code into the container
      - ./backend-drive-nip:/app
      # Creates an anonymous volume for node_modules to prevent it from being overwritten by the host
      - /app/node_modules
    # Overrides the Dockerfile's CMD to use nodemon for auto-restarting
    command: sh -c "npm install && npm run dev"
    restart: always

  frontend:
    # NOTE: This configuration is for DEVELOPMENT. It overrides the production Dockerfile.
    # It uses the node image directly to run the Vite dev server.
    image: node:22-alpine
    container_name: frontend-nip-app-container
    working_dir: /app
    ports:
      # Exposes the Vite dev server port (default is 5173)
      - "5173:5173"
    volumes:
      # Mounts the host's source code into the container
      - ./frontend-nip-app:/app
      # Creates an anonymous volume for node_modules to prevent it from being overwritten by the host
      - /app/node_modules
    # Command to install dependencies and start the Vite dev server with HMR
    # The server will be accessible on http://localhost:5173
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
    restart: always